import { useState } from "react";

export default function DisclaimerPage() {
  const [activeTab, setActiveTab] = useState<"risk"|"privacy"|"terms">("risk");

  const tabStyle = (t: string) => ({
    padding: "8px 16px", borderRadius: 4, fontSize: 10, fontWeight: 700 as const,
    cursor: "pointer" as const, letterSpacing: 1, fontFamily: "inherit", border: "none",
    background: activeTab === t ? "#00ff88" : "transparent",
    color: activeTab === t ? "#030810" : "#3a6080",
  });

  return (
    <div style={{background:"#030810",minHeight:"100vh",fontFamily:"'SF Mono','Fira Code',monospace",color:"#e0e8f0",paddingBottom:60}}>

      {/* TOPBAR */}
      <div style={{background:"#050d1a",borderBottom:"1px solid #0d2035",padding:"10px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",position:"sticky",top:0,zIndex:100}}>
        <a href="/" style={{fontSize:18,fontWeight:700,letterSpacing:2,color:"#00ff88",textDecoration:"none"}}>PREDIQ</a>
        <div style={{display:"flex",gap:12}}>
          <a href="/" style={{fontSize:10,color:"#3a6080",textDecoration:"none",border:"1px solid #0d2035",padding:"4px 12px",borderRadius:4}}>← HOME</a>
          <a href="/" style={{fontSize:10,color:"#00ff88",textDecoration:"none",border:"1px solid #00ff88",padding:"4px 12px",borderRadius:4}}>ENTER APP</a>
        </div>
      </div>

      <div style={{maxWidth:780,margin:"0 auto",padding:"32px 24px"}}>

        {/* HEADER */}
        <div style={{marginBottom:24}}>
          <div style={{fontSize:9,color:"#3a6080",letterSpacing:2,marginBottom:6}}>LEGAL</div>
          <div style={{fontSize:24,fontWeight:700,color:"#e0e8f0",marginBottom:4}}>Legal & Privacy</div>
          <div style={{fontSize:11,color:"#3a6080"}}>PREDIQ Time Machine — Trinovion Technology AI — Last updated March 2026</div>
        </div>

        {/* TABS */}
        <div style={{display:"flex",gap:2,marginBottom:20,background:"#050d1a",borderRadius:6,padding:3,border:"1px solid #0d2035",width:"fit-content"}}>
          <button onClick={()=>setActiveTab("risk")} style={tabStyle("risk")}>RISK DISCLAIMER</button>
          <button onClick={()=>setActiveTab("privacy")} style={tabStyle("privacy")}>PRIVACY POLICY</button>
          <button onClick={()=>setActiveTab("terms")} style={tabStyle("terms")}>TERMS OF USE</button>
        </div>

        {/* RISK DISCLAIMER */}
        {activeTab==="risk" && (
          <div>
            <div style={{background:"#1a0008",border:"1px solid #ff4466",borderRadius:8,padding:"14px 18px",marginBottom:20,display:"flex",gap:10,alignItems:"flex-start"}}>
              <div style={{width:8,height:8,borderRadius:"50%",background:"#ff4466",flexShrink:0,marginTop:3}}/>
              <div style={{fontSize:11,fontWeight:700,color:"#ff4466",lineHeight:1.7}}>
                IMPORTANT: PREDIQ Time Machine is NOT a licensed financial advisor. All signals are for educational and research purposes only. Trading involves significant risk of loss.
              </div>
            </div>

            {[
              ["NOT FINANCIAL ADVICE",
               "PREDIQ Time Machine and all content, signals, predictions, forecasts and analysis generated by the Miro Fish swarm engine are provided for informational and educational purposes only. Nothing on this platform constitutes financial advice, investment advice, trading advice, or any other form of professional financial guidance. You should not make any financial decision based solely on information provided by PREDIQ."],
              ["NOT SEBI / REGULATORY REGISTERED",
               "PREDIQ Time Machine and Trinovion Technology AI are not registered with the Securities and Exchange Board of India (SEBI), the Financial Conduct Authority (FCA), the Securities and Exchange Commission (SEC), the Comision para el Mercado Financiero (CMF) of Chile, or any other financial regulatory authority globally. We do not provide regulated investment services or advice."],
              ["ACCURACY DISCLAIMER",
               "The accuracy statistics displayed (79.2% overall, 83.4% filtered high-confidence signals) represent historical performance of the PREDIQ swarm engine during a live private beta period. Past performance is not indicative of future results. No AI system, algorithm or prediction model can guarantee profitable trading outcomes. Markets can and do move unpredictably."],
              ["BETA SOFTWARE WARNING",
               "PREDIQ is currently in private beta. The platform may contain bugs, errors, delays or inaccuracies. Signals may be delayed, incorrect or temporarily unavailable. Do not make trading decisions assuming PREDIQ will function correctly at any given time. Always verify signals with your own research."],
              ["RISK OF CAPITAL LOSS",
               "Trading and investing in stocks, commodities, forex, cryptocurrencies and other financial instruments involves significant risk. You may lose some or all of your invested capital. Never trade with money you cannot afford to lose. Always use appropriate risk management including stop-loss orders. Always consult a licensed financial advisor before making investment decisions."],
              ["DATA SOURCES & DELAYS",
               "Market prices are sourced from Yahoo Finance via yfinance. Data may be delayed by up to 15 minutes during market hours. PREDIQ does not guarantee the accuracy, completeness or timeliness of any market data. Prices shown may differ from your broker's prices."],
              ["LIMITATION OF LIABILITY",
               "Trinovion Technology AI, PREDIQ Time Machine, its founders, employees and affiliates accept no liability whatsoever for any financial losses, damages or costs incurred as a result of using information from this platform. By using PREDIQ you acknowledge and accept all risks associated with AI-generated market signals."],
            ].map(([title, body]) => (
              <div key={title} style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
                <div style={{fontSize:9,fontWeight:700,color:"#ff4466",letterSpacing:2,marginBottom:8}}>{title}</div>
                <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>{body}</div>
              </div>
            ))}
          </div>
        )}

        {/* PRIVACY POLICY */}
        {activeTab==="privacy" && (
          <div>
            <div style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
              <div style={{fontSize:9,fontWeight:700,color:"#00ff88",letterSpacing:2,marginBottom:8}}>WHAT WE COLLECT</div>
              <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>
                When you join the PREDIQ waitlist we collect your email address. This is the only personal information we collect. We do not collect your name, phone number, payment details or any other personal data during the beta period.
              </div>
            </div>
            <div style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
              <div style={{fontSize:9,fontWeight:700,color:"#00ff88",letterSpacing:2,marginBottom:8}}>HOW WE USE YOUR EMAIL</div>
              <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>
                Your email is used solely to send you your beta access code and occasional product updates. We will never sell your email to third parties. We will never send you spam. You can unsubscribe at any time by replying to any email with "UNSUBSCRIBE".
              </div>
            </div>
            <div style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
              <div style={{fontSize:9,fontWeight:700,color:"#00ff88",letterSpacing:2,marginBottom:8}}>COOKIES & TRACKING</div>
              <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>
                PREDIQ does not use advertising cookies or third-party tracking. We use Netlify for hosting which may set basic session cookies for performance. We do not use Google Analytics, Facebook Pixel or any advertising trackers.
              </div>
            </div>
            <div style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
              <div style={{fontSize:9,fontWeight:700,color:"#00ff88",letterSpacing:2,marginBottom:8}}>SIGNAL DATA</div>
              <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>
                Swarm signals generated during your session are logged anonymously for accuracy tracking purposes. No personally identifiable information is attached to signal logs. Signal data is used to improve the accuracy of the PREDIQ engine.
              </div>
            </div>
            <div style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
              <div style={{fontSize:9,fontWeight:700,color:"#00ff88",letterSpacing:2,marginBottom:8}}>DATA STORAGE</div>
              <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>
                Email addresses are stored securely via Web3Forms. Market signal data is stored on Railway (Europe West region). We comply with GDPR principles. You may request deletion of your data at any time by emailing george10198@gmail.com.
              </div>
            </div>
            <div style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
              <div style={{fontSize:9,fontWeight:700,color:"#00ff88",letterSpacing:2,marginBottom:8}}>CONTACT</div>
              <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>
                For any privacy concerns contact: george10198@gmail.com — Vinayraj George, Trinovion Technology AI, Santiago, Chile.
              </div>
            </div>
          </div>
        )}

        {/* TERMS OF USE */}
        {activeTab==="terms" && (
          <div>
            {[
              ["ACCEPTANCE OF TERMS",
               "By accessing PREDIQ Time Machine you agree to these Terms of Use. If you do not agree, do not use the platform. These terms may be updated at any time. Continued use after updates constitutes acceptance."],
              ["BETA ACCESS",
               "PREDIQ is currently in private beta. Access is granted via invitation only using a beta access code. You may not share your beta code publicly. Beta access may be revoked at any time at our discretion. Beta access is free and does not constitute a commercial agreement."],
              ["PERMITTED USE",
               "You may use PREDIQ for personal research, education and information purposes only. You may not use PREDIQ signals for commercial trading advisory services, copy trading platforms, or any service that redistributes PREDIQ signals to third parties without written permission from Trinovion Technology AI."],
              ["INTELLECTUAL PROPERTY",
               "The Miro Fish swarm engine, PREDIQ Time Machine brand, all algorithms, code, designs and content are the intellectual property of Trinovion Technology AI. You may not copy, reproduce, reverse engineer or distribute any part of PREDIQ without written permission."],
              ["NO WARRANTY",
               "PREDIQ is provided AS IS without any warranty of any kind. We do not warrant that the platform will be uninterrupted, error-free or that signals will be accurate. All use is at your own risk."],
              ["GOVERNING LAW",
               "These terms are governed by the laws of Chile. Any disputes shall be subject to the jurisdiction of the courts of Santiago, Chile."],
              ["CONTACT",
               "For any queries regarding these terms contact: george10198@gmail.com — Trinovion Technology AI, Santiago, Chile."],
            ].map(([title, body]) => (
              <div key={title} style={{background:"#050d1a",border:"1px solid #0d2035",borderRadius:8,padding:"14px 18px",marginBottom:10}}>
                <div style={{fontSize:9,fontWeight:700,color:"#ffaa00",letterSpacing:2,marginBottom:8}}>{title}</div>
                <div style={{fontSize:11,color:"#8ab0cc",lineHeight:1.8}}>{body}</div>
              </div>
            ))}
          </div>
        )}

        {/* BOTTOM BUTTONS */}
        <div style={{marginTop:28,display:"flex",gap:12,justifyContent:"center",flexWrap:"wrap"}}>
          <a href="/" style={{padding:"10px 24px",borderRadius:4,border:"1px solid #0d2035",color:"#3a6080",fontSize:11,fontWeight:700,letterSpacing:2,textDecoration:"none",fontFamily:"inherit"}}>
            ← BACK TO HOME
          </a>
          <a href="/" style={{padding:"10px 24px",borderRadius:4,border:"1px solid #00ff88",color:"#00ff88",fontSize:11,fontWeight:700,letterSpacing:2,textDecoration:"none",fontFamily:"inherit"}}>
            I UNDERSTAND — ENTER PREDIQ →
          </a>
        </div>

        <div style={{marginTop:20,textAlign:"center",fontSize:9,color:"#1a3a5c",lineHeight:1.7}}>
          PREDIQ Time Machine · Trinovion Technology AI · Santiago, Chile<br/>
          Not a licensed financial advisor · Not SEBI registered · Beta software<br/>
          george10198@gmail.com
        </div>
      </div>
    </div>
  );
}
